# Basic NumPy intro

In [1]:
import numpy as np # This is alias

ml=[1,2,3,4,5,6,7,8]
a=np.array(ml,dtype=int)
print(a)

[1 2 3 4 5 6 7 8]


In [22]:
arr=a.reshape(2,4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


# Multi-Dimension Array


In [31]:

print(np.array(np.arange(0,15)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [38]:
t1 = (1, 2, "tuple", 4)
t2 = (5, 6, 7)
x=t2[t1[1]]
t3=(list(t1),list(t2))
t3=(t1,t2)
t3=t1+t2

In [41]:
student = {'name': 'Jane', 'age': 25, 'courses': ['Math', 'Statistics']}
student.update({'age' : 26, 'phone': '123-456'})
student['phone'] = '123-456'
student.update({'age' : 26})